### PR TITLE
Fix paginated list scroll events

### PR DESCRIPTION
**Pull request by PVGeorgievPrime**
#622

### CODE REVIEW

**Review by StanevPrime — APPROVED** [review]

**Review by StanevPrime — CHANGES_REQUESTED** [review]
Please adjust the version in the pubspec

**Comment by PVGeorgievPrime** [comment]
> Please adjust the version in the pubspec

Done

**Review by StanevPrime — APPROVED** [review]

**Review by DDavidPrime — APPROVED** [review]

**Comment by DDavidPrime** [comment]
After testing the app, the implementation works correctly. However there are two additional things I noticed:
1. The bottom loading indicator is appearing even when we do a pull-to-refresh
2. If the user pulls-to-refresh and then quickly, before the data is refreshed, scrolls to the bottom of the list (much easier in shorter lists), the initial data (entries 0-4) is discarded and the list starts from the next page fetched when scrolled to bottom (entries 5-9).

https://github.com/Prime-Holding/rx_bloc/assets/61236867/e96929fd-1ed4-43f8-93f6-c03ab3fcab95

**Comment by StanevPrime** [comment]
@PVGeorgievPrime, please fix the mentioned above issue before merging this PR

**Comment by StanevPrime** [comment]
@PVGeorgievPrime, are they any remaining action items on this SR ?

**Review by StanevPrime — APPROVED** [review]

**Review by StanevPrime — CHANGES_REQUESTED** [review]
Please add unit tests needed for the fix

**Comment by PVGeorgievPrime** [comment]
> Please add unit tests needed for the fix

Done

**Review by StanevPrime — APPROVED** [review]

**Review by DDavidPrime — APPROVED** [review]

**Pull request merged**
