### PR TITLE
rx_bloc_generator: Add support for generic blocs

### PR DESCRIPTION
**Pull request by jld3103**
Previously we got
```dart
abstract class $GenericBloc extends RxBlocBase implements GenericBlocEvents, GenericBlocStates, GenericBlocType {}
```
from
```dart
class GenericBloc<T> extends $GenericBloc {}
```
Now we get
```dart
abstract class $GenericBloc<T> extends RxBlocBase implements GenericBlocEvents, GenericBlocStates, GenericBlocType {}
```
which works.

### CODE REVIEW

**Comment by StanevPrime** [comment]
Thanks for your contribution!. 

The proposed feature looks good, but may I ask you to add tests for this enhancement ?

Also, please make sure the base of your PR is `develop`, not `master`

**Review by StanevPrime — CHANGES_REQUESTED** [review]
Thanks for your contribution!.

The proposed feature looks good, but may I ask you to add tests for this enhancement ?

Also, please make sure the base of your PR is develop, not master

**Review by StanevPrime — CHANGES_REQUESTED** [review]
Thanks for your contribution!.

The proposed feature looks good, but may I ask you to add tests for this enhancement ?

**Comment by jld3103** [comment]
hi, i'll check what i can do. i can't exactly remember which company project this was for, but i'll find it and update this PR with your request.

**Comment by jld3103** [comment]
sorry for not following up, i will finish this after my vacation :smile:

**Comment by jld3103** [comment]
@StanevPrime rebased and add a test :tada:

**Review by StanevPrime — APPROVED** [review]

**Pull request merged**
